In [4]:
a=[2,3,4]
[q*2 for q in a]

[4, 6, 8]

## 1. Les vecteurs, les tableaux 1D
### Initialisation vectorielle

# Une façon de créer un tableau NumPy consiste à convertir une liste Python.
# Le type sera automatiquement déduit des types d'éléments de la liste

In [23]:
import numpy as np
a=np.array([5,6,8])
a+2

array([ 7,  8, 10])

In [24]:
a=[2,4,6]
b=[8]
[q+r for q,r in zip(a,b)]

[10]

In [13]:
c=np.array([5,6,8])
d=np.array([2])
c+d

array([ 7,  8, 10])

In [29]:
a=np.array([2.,9.,6.])
a

array([2., 9., 6.])

In [14]:
c=np.array([5,6,8])
d=np.array([2])
c-d

array([3, 4, 6])

In [15]:
c=np.array([5,6,8])
d=np.array([2])
c//d

array([2, 3, 4], dtype=int32)

In [16]:
c=np.array([5,6,8])
d=np.array([2])
c*d

array([10, 12, 16])

In [12]:
a=np.array([5,6,8])
a

array([5, 6, 8])

In [19]:
c=np.array(['sd','gh',2,5])
c

array(['sd', 'gh', '2', '5'], dtype='<U11')

In [52]:
a=np.array([2,5,3])
a

array([2, 5, 3])

In [53]:
b=np.zeros(3,int)
b

array([0, 0, 0])

In [54]:
c=np.zeros_like(a)
c

array([0, 0, 0])

In [57]:
np.zeros(3)

array([0., 0., 0.])

In [75]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [83]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [90]:
np.full(3,7.)

array([7., 7., 7.])

In [115]:
m=np.array([1,2,3,6])
m

array([1, 2, 3, 6])

In [116]:
np.zeros_like(m)

array([0, 0, 0, 0])

In [117]:
np.ones_like(m)

array([1, 1, 1, 1])

In [118]:
np.empty_like(m)

array([24379518, 27459700,   -65401,   -65509])

In [119]:
np.full_like(m,6)

array([6, 6, 6, 6])

In [120]:
m=np.array([1,2,3,6])
m

array([1, 2, 3, 6])

In [128]:
m[2]

3

In [129]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [130]:
np.arange(7,9)

array([7, 8])

In [132]:
e=np.arange(1,19,7)
e

array([ 1,  8, 15])

In [133]:
type(e)

numpy.ndarray

In [161]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [169]:
np.random.randint(5,9,4)

array([8, 7, 8, 7])

In [180]:
np.random.rand(1)

array([0.34402918])

In [184]:
np.random.uniform(1,10,2)

array([7.95955091, 6.11538596])

In [185]:
np.random.randn(1)

array([2.59058389])

In [189]:
rng = np.random.default_rng()

In [190]:
rng.integers(0,10,3)

array([4, 9, 5], dtype=int64)

In [194]:
rng.random(4)

array([0.75960658, 0.12141878, 0.28099223, 0.4578737 ])

In [195]:
rng.uniform(1,10,3)

array([3.61343012, 3.77404859, 6.99137513])

In [197]:
rng.normal(5,2,3)

array([5.84938612, 3.67119153, 6.22829048])

## Indexation vectorielle

In [3]:
import numpy as np
a=np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [4]:
a[1]

2

In [5]:
a[0:3]

array([1, 2, 3])

In [8]:
a[-3::]

array([3, 4, 5])

In [13]:
a[::-1]

array([5, 4, 3, 2, 1])

In [254]:
a[::2]

array([1, 3, 5])

In [256]:
a[2:4]=0
a

array([1, 2, 0, 0, 5])

In [258]:
a[[1,3,4]]

array([2, 0, 5])

In [260]:
d=[1,2,3]
d[1:2] = [9,6]
d


[1, 9, 6, 3]

In [271]:
a=np.array([1,2,5,4,6,7,8,5,4,2])
a

array([1, 2, 5, 4, 6, 7, 8, 5, 4, 2])

In [272]:
a > 5

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [273]:
a[ a > 5]

array([6, 7, 8])

In [274]:
np.any(a>5)

True

In [276]:
np.all(a>5)

False

In [277]:
a[a>5]=0


In [278]:
a

array([1, 2, 5, 4, 0, 0, 0, 5, 4, 2])

In [279]:
a[(a>=3) & (a<=5)]=0

In [280]:
a

array([1, 2, 0, 0, 0, 0, 0, 0, 0, 2])

## Opérations vectorielles

In [282]:
a=np.array([2,3])
z=np.array([8,3])
a-z

array([-6,  0])

In [283]:
a**z

array([256,  27], dtype=int32)

In [284]:
a-z

array([-6,  0])

In [285]:
a+z

array([10,  6])

In [286]:
a/z


array([0.25, 1.  ])

In [287]:
a**2

array([4, 9], dtype=int32)

In [289]:
np.sqrt(a**2)

array([2., 3.])

In [290]:
np.exp(a)

array([ 7.3890561 , 20.08553692])

In [291]:
np.log(a)

array([0.69314718, 1.09861229])

In [293]:
np.dot(a,z)

25